# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-14 11:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientVisitReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prepared_by', models.CharField(max_length=200)),
                ('visit_location', models.CharField(max_length=200)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('reason_for_visit', models.TextField(blank=True, max_length=1500, null=True)),
                ('actions_taken_during_the_visit', models.TextField(blank=True, max_length=1500, null=True)),
                ('next_plan_of_action', models.TextField(blank=True, max_length=1500, null=True)),
                ('comments', models.TextField(blank=True, max_length=1500, null=True)),
                ('reason_for_reject', models.TextField(blank=True, max_length=200, null=True)),
                ('date_of_approval', models.DateTimeField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_rejected', models.BooleanField(default=False)),
                ('client_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile', verbose_name='Client Details')),
                ('project_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Project', verbose_name='project name')),
                ('reporting_senior_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ClientVisitReport',
                'verbose_name_plural': 'clientvisitreports',
            },
        ),
    ]
